server:
  port: 8910

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chapter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jl19970415
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      location: D:/springboot-multipart
      max-file-size: 5MB
      max-request-size: 20MB
  messages:
    encoding: UTF-8
    basename: international
    cache-duration: 30s
#    date-format: yyyy-MM-dd
logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
      org:
        mybatis: DEBUG

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.springboot.chapter10.pojo