server:
  port: 8915

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chapter?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: jl19970415
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
      default-transaction-isolation: 2
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2s
    timeout: 1s
#  security:
#    user:
#      name: user
#      password: aaa111
#      roles: user

logging:
  level:
    root: info
#    org:
#      springframework: debug
#      org:
#        mybatis: debug
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.springboot.chapter15.pojo