server:
  port: 8905

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chapter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jl19970415
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,log4j
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.chapter5.pojo
  type-handlers-package: com.springboot.chapter5.typehandler
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG
      org:
        mybatis: DEBUG