server:
  port: 8914

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chapter?useUnicode=true&useSSL=trus&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: jl19970415
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springboot
      username: root
      password: jl19970415
  webflux:
    date-format: yyyy-MM-dd
    static-path-pattern: /static/**

logging:
  level:
    root: debug
    org:
      springframework: debug